### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'unsqueeze

### ISSUE THREAD

**Issue by Mikerhinos** [ashawkey/InTeX#5]
Hello,

I installed InTeX in a python venv and am getting this error when trying the gradio app, I tried with a obj and a glb mesh.

[INFO] start generation...
  0%|                                                                                                                                                                          | 0/11 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\gradio\queueing.py", line 522, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\gradio\route_utils.py", line 260, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\gradio\blocks.py", line 1689, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\gradio\blocks.py", line 1255, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\gradio\utils.py", line 750, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\app.py", line 25, in process
    core.generate()
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\main.py", line 474, in generate
    self.inpaint_view(pose)
  File "C:\Users\Mikerhinos\InTeX\intex\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\main.py", line 151, in inpaint_view
    out = self.renderer.render(pose, self.cam.perspective, H, W)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikerhinos\InTeX\mesh_renderer.py", line 108, in render
    texc, texc_db = dr.interpolate(self.mesh.vt.unsqueeze(0).contiguous(), rast, self.mesh.ft, rast_db=rast_db, diff_attrs='all')
                                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'unsqueeze'

Edit : it's a AI generated mesh, I just tried with a stl file (so no texture) and it worked.

**Comment by Mikerhinos** [comment]
I opened my AI generated mesh in Blender, re exported in obj unticking the "Export material" so it's just the mesh, and it's working fine.
Closing.
